# Pandas

- created by Wes McKinney, 2008
- used for working with big datasets and make conclusions based on statistics and make it readable and relevent (analyzing, cleaning, manipulating)

## pandas series
it is like a column in a table (1-D array holding data of any type)

In [2]:
import pandas as pd

In [5]:
a=[1,7,2]
x=pd.Series(a)
print(x)
print(type(x))

0    1
1    7
2    2
dtype: int64
<class 'pandas.core.series.Series'>

In [6]:
print(x[1])

7

change name of index

In [7]:
a=[1,7,2]
x=pd.Series(a, index=["x","y","z"])
print(x)
print(type(x))

x    1
y    7
z    2
dtype: int64
<class 'pandas.core.series.Series'>

In [8]:
print(x[1])

7

In [9]:
print(x["y"])

7

In [11]:
b=(1.4,2,3,4)
y=pd.Series(b)
print(y)
print(type(y))

0    1.4
1    2.0
2    3.0
3    4.0
dtype: float64
<class 'pandas.core.series.Series'>

In [13]:
name=["ram","shyam","radha","geeta","seeta"]
marks=[50,60,70,80,90]
z=pd.Series(marks,index=name, name='student result')
print(z)

ram      50
shyam    60
radha    70
geeta    80
seeta    90
Name: student result, dtype: int64

In [16]:
calories={'day1':400, 'day2':380, 'day3':430, 'day4':390}
c=pd.Series(calories)
print(c)

day1    400
day2    380
day3    430
day4    390
dtype: int64

In [17]:
calories={'day1':400, 'day2':380, 'day3':430, 'day4':390}
c=pd.Series(calories, index=['day1','day2'])
print(c)

day1    400
day2    380
dtype: int64

In [18]:
calories={'day1':400, 'day2':380, 'day3':430, 'day4':390}
c=pd.Series(calories, name="calories burn per day")
print(c)

day1    400
day2    380
day3    430
day4    390
Name: calories burn per day, dtype: int64

series attributes

In [19]:
c.size

4

In [20]:
c.dtype

dtype('int64')

In [21]:
c.name

'calories burn per day'

In [22]:
c.index

Index(['day1', 'day2', 'day3', 'day4'], dtype='object')

In [25]:
c.values
# gives list in output

array([400, 380, 430, 390], dtype=int64)

In [26]:
print(c.values)
# gives output as array

[400 380 430 390]

In [27]:
print(type(c.values))

<class 'numpy.ndarray'>

In [28]:
c.is_unique

True

In [30]:
print(pd.Series([55,22,33,44,55]).is_unique)
# 55 is written twice, means not all values are unique hence False

False

In [32]:
subs=pd.read_csv('subs.csv')
print(subs)

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [35]:
subs=pd.read_csv('subs.csv')
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [36]:
subs=pd.read_csv('subs.csv')
type(subs)

pandas.core.frame.DataFrame

In [39]:
subs=pd.read_csv('subs.csv', squeeze=True) #converts dataframe to series
# squeeze=True or ('subs.csv').squeeze
type(subs)

pandas.core.series.Series

In [40]:
subs.min()

33

In [41]:
subs.max()

396

In [42]:
subs.median()

123.0

In [43]:
subs.sum()

49510

In [44]:
subs[subs>200]

165    225
166    249
167    265
168    306
169    261
170    222
225    224
226    254
227    214
228    236
229    261
230    247
231    207
232    254
233    301
234    233
240    202
246    259
248    213
249    210
252    216
275    228
276    237
277    276
279    290
280    295
281    245
282    241
283    267
284    269
285    211
287    206
288    202
290    236
291    222
292    203
312    230
318    244
324    243
325    227
326    259
330    396
331    312
332    268
333    229
337    221
338    225
339    221
340    202
344    276
345    258
346    219
347    212
351    220
354    204
358    210
359    209
360    231
361    226
Name: Subscribers gained, dtype: int64

In [45]:
subs[subs>200].size

59

In [48]:
b=pd.read_csv('bollywood.csv')
b

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [49]:
b.min()

movie    1920 (film)
lead      Aadar Jain
dtype: object

In [50]:
b.max()

movie    Zor Lagaa Ke...Haiya!
lead               Zulfi Sayed
dtype: object

In [51]:
b.median()

Series([], dtype: float64)

In [59]:
movies=pd.read_csv('bollywood.csv', index_col='movie', squeeze=True)
print(movies)

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [60]:
movies.head() #gives first 5 by deafult

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
Name: lead, dtype: object

In [61]:
movies.head(10)

movie
Uri: The Surgical Strike                       Vicky Kaushal
Battalion 609                                    Vicky Ahuja
The Accidental Prime Minister (film)             Anupam Kher
Why Cheat India                                Emraan Hashmi
Evening Shadows                             Mona Ambegaonkar
Soni (film)                             Geetika Vidya Ohlyan
Fraud Saiyaan                                   Arshad Warsi
Bombairiya                                      Radhika Apte
Manikarnika: The Queen of Jhansi              Kangana Ranaut
Thackeray (film)                         Nawazuddin Siddiqui
Name: lead, dtype: object

In [62]:
movies.tail() #gives first 5 by deafult

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: object

In [63]:
movies[0]

'Vicky Kaushal'

In [65]:
movies['Uri: The Surgical Strike']

'Vicky Kaushal'

In [66]:
movies[::2]

movie
Uri: The Surgical Strike                   Vicky Kaushal
The Accidental Prime Minister (film)         Anupam Kher
Evening Shadows                         Mona Ambegaonkar
Fraud Saiyaan                               Arshad Warsi
Manikarnika: The Queen of Jhansi          Kangana Ranaut
                                              ...
Raaz (2002 film)                              Dino Morea
Waisa Bhi Hota Hai Part II                  Arshad Warsi
Kaante                                  Amitabh Bachchan
Aankhen (2002 film)                     Amitabh Bachchan
Company (film)                                Ajay Devgn
Name: lead, Length: 750, dtype: object

In [67]:
movies[[0,1,3,6,8]]

movie
Uri: The Surgical Strike             Vicky Kaushal
Battalion 609                          Vicky Ahuja
Why Cheat India                      Emraan Hashmi
Fraud Saiyaan                         Arshad Warsi
Manikarnika: The Queen of Jhansi    Kangana Ranaut
Name: lead, dtype: object

In [68]:
movies[-5:0]

Series([], Name: lead, dtype: object)

In [70]:
'Kaante' in movies

True

In [71]:
'Ajay Devgn' in movies.values

True