In [2]:
API_key='96e6a25a7a7961eb790c459a27a96c9e'

In [2]:
import requests, json

### geocoding api for lat and lon

In [4]:
def get_coords():
    api_key='96e6a25a7a7961eb790c459a27a96c9e'
    city=input('Enter city name : ')
    request_url=f'http://api.openweathermap.org/geo/1.0/direct?q={city}&limit=5&appid={api_key}'
    result=requests.get(request_url)
    c=result.json()
    print(json.dumps(c,indent=5))
    latitude=c[0]['lat']
    longitude=c[0]['lon']
    return latitude,longitude,city
lat,lon,city=get_coords()
print(city)
print("latitude",lat)
print("longitude",lon)

Enter city name :  Ahmedabad

[
     {
          "name": "Ahmedabad",
          "local_names": {
               "gu": "\u0a85\u0aae\u0aa6\u0abe\u0ab5\u0abe\u0aa6",
               "ja": "\u30a2\u30d5\u30de\u30c0\u30fc\u30d0\u30fc\u30c9",
               "or": "\u0b05\u0b39\u0b2e\u0b26\u0b3e\u0b2c\u0b3e\u0b26",
               "feature_name": "Ahmedabad",
               "ml": "\u0d05\u0d39\u0d2e\u0d4d\u0d2e\u0d26\u0d3e\u0d2c\u0d3e\u0d26\u0d4d",
               "pl": "Ahmadabad",
               "ur": "\u0627\u062d\u0645\u062f \u0622\u0628\u0627\u062f",
               "ar": "\u0623\u062d\u0645\u062f \u0622\u0628\u0627\u062f",
               "de": "Ahmedabad",
               "oc": "Ahmadabad",
               "hi": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
               "en": "Ahmedabad",
               "he": "\u05d0\u05d7\u05de\u05d3\u05d0\u05d1\u05d0\u05d3",
               "pa": "\u0a05\u0a39\u0a3f\u0a2e\u0a26\u0a3e\u0a2c\u0a3e\u0a26",
               "tt": "\u04d8\u0445\u043c\u04d9\u0442\u0430\u0431\u0430\u0434",
               "bn": "\u0986\u09b9\u09ae\u09c7\u09a6\u09be\u09ac\u09be\u09a6",
               "eo": "Ahmadabado",
               "ascii": "Ahmedabad",
               "cs": "Ahmad\u00e1b\u00e1d",
               "te": "\u0c05\u0c39\u0c4d\u0c2e\u0c26\u0c3e\u0c2c\u0c3e\u0c26\u0c4d",
               "ne": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
               "ru": "\u0410\u0445\u043c\u0430\u0434\u0430\u0431\u0430\u0434",
               "uk": "\u0410\u0445\u043c\u0435\u0434\u0430\u0431\u0430\u0434",
               "kn": "\u0c85\u0cb9\u0ccd\u0cae\u0ca6\u0cbe\u0cac\u0cbe\u0ca6\u0ccd",
               "ta": "\u0b85\u0b95\u0bae\u0ba4\u0bbe\u0baa\u0bbe\u0ba4\u0bcd",
               "zh": "\u827e\u54c8\u8fc8\u8fbe\u5df4\u5fb7",
               "mr": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926"
          },
          "lat": 23.0215374,
          "lon": 72.5800568,
          "country": "IN",
          "state": "Gujarat"
     },
     {
          "name": "Ahmedabad",
          "local_names": {
               "en": "Ahmedabad"
          },
          "lat": 32.5022729,
          "lon": 72.8536319,
          "country": "PK",
          "state": "Punjab"
     },
     {
          "name": "Ahmedabad",
          "local_names": {
               "en": "Ahmedabad"
          },
          "lat": 24.7312039,
          "lon": 67.6891818,
          "country": "PK",
          "state": "Sindh"
     },
     {
          "name": "Ahmedabad",
          "lat": 32.9649355,
          "lon": 74.2725539,
          "country": "PK",
          "state": "Azad Kashmir"
     },
     {
          "name": "Ahmedabad",
          "local_names": {
               "en": "Ahmedabad"
          },
          "lat": 31.4963792,
          "lon": 72.0759963,
          "country": "PK",
          "state": "Punjab"
     }
]
Ahmedabad
latitude 23.0215374
longitude 72.5800568

### Current Weather

In [5]:
def current_weather():
    api_key='96e6a25a7a7961eb790c459a27a96c9e'
    request_url=f'https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={api_key}'
    result=requests.get(request_url)
    w=result.json()
    print(json.dumps(w,indent=5))
    descript=w['weather'][0]['description']
    temp=w['main']['temp']
    pressure=w['main']['pressure']
    humidity=w['main']['humidity']
    windspeed=w['wind']['speed']
    visibility=w['visibility']
    print()
    print("weather description : ",descript)
    print("temperature : ",temp)
    print("pressure : ",pressure)
    print("humidity : ",humidity)
    print("wind speed : ",windspeed)
    print("visibility : ",visibility)
current_weather()

{
     "coord": {
          "lon": 72.5797,
          "lat": 23.0216
     },
     "weather": [
          {
               "id": 711,
               "main": "Smoke",
               "description": "smoke",
               "icon": "50d"
          }
     ],
     "base": "stations",
     "main": {
          "temp": 308.19,
          "feels_like": 309.86,
          "temp_min": 308.19,
          "temp_max": 308.19,
          "pressure": 1006,
          "humidity": 38,
          "sea_level": 1006,
          "grnd_level": 1001
     },
     "visibility": 4000,
     "wind": {
          "speed": 8.23,
          "deg": 160
     },
     "clouds": {
          "all": 1
     },
     "dt": 1780121309,
     "sys": {
          "type": 1,
          "id": 9049,
          "country": "IN",
          "sunrise": 1780100664,
          "sunset": 1780149018
     },
     "timezone": 19800,
     "id": 1279233,
     "name": "Ahmedabad",
     "cod": 200
}

weather description :  smoke
temperature :  308.19
pressure :  1006
humidity :  38
wind speed :  8.23
visibility :  4000

### Air pollution

In [6]:
def ap():
    api_key='96e6a25a7a7961eb790c459a27a96c9e'
    request_url=f'http://api.openweathermap.org/data/2.5/air_pollution?lat={lat}&lon={lon}&appid={api_key}'
    result=requests.get(request_url)
    a=result.json()
    print(json.dumps(a,indent=5))
    quality_index={1:'good',2:'fair',3:'moderate',4:'poor',5:'very poor'}
    aqi=a['list'][0]['main']['aqi']
    print("AQI : ",aqi)
    print(quality_index[aqi])
ap()

{
     "coord": {
          "lon": 72.5801,
          "lat": 23.0215
     },
     "list": [
          {
               "main": {
                    "aqi": 2
               },
               "components": {
                    "co": 88.65,
                    "no": 0.15,
                    "no2": 0.62,
                    "o3": 52.3,
                    "so2": 1.06,
                    "pm2_5": 5.65,
                    "pm10": 26.31,
                    "nh3": 0.57
               },
               "dt": 1780121125
          }
     ]
}
AQI :  2
fair

In [8]:
def forecast():
    api_key='96e6a25a7a7961eb790c459a27a96c9e'

    city=input('Enter city name : ')
    request_url=f'http://api.openweathermap.org/geo/1.0/direct?q={city}&limit=5&appid={api_key}'
    result=requests.get(request_url)
    c=result.json()
    # print(json.dumps(c,indent=5))
    latitude=c[0]['lat']
    longitude=c[0]['lon']
    request_url=f'https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={api_key}'
    result=requests.get(request_url)
    a=result.json()
    # print(json.dumps(a,indent=5))
    return a
fiveDay=forecast()

Enter city name :  Ahmedabad

In [10]:
import pandas as pd

In [11]:
data={"Date_Time":[],"Temperature":[],"Pressure":[],"Humidity":[],"Wind speed":[],"Visibility":[], "Description":[]}
for i in fiveDay['list']:
    data['Date_Time'].append(i['dt_txt'])
    data['Description'].append(i['weather'][0]['description'])
    data['Temperature'].append(i['main']['temp'])
    data['Pressure'].append(i['main']['pressure'])
    data['Humidity'].append(i['main']['humidity'])
    data['Wind speed'].append(i['wind']['speed'])
    data['Visibility'].append(i['visibility'])
df=pd.DataFrame(data)
df

,Date_Time,Temperature,Pressure,Humidity,Wind speed,Visibility,Description
0,2026-05-30 09:00:00,309.81,1005,33,6.67,10000,clear sky
1,2026-05-30 12:00:00,312.32,1003,27,7.23,10000,clear sky
2,2026-05-30 15:00:00,308.42,1003,41,3.34,10000,clear sky
3,2026-05-30 18:00:00,305.35,1006,55,3.65,10000,clear sky
4,2026-05-30 21:00:00,303.48,1005,62,4.87,10000,clear sky
5,2026-05-31 00:00:00,302.20,1007,68,4.17,10000,clear sky
6,2026-05-31 03:00:00,304.64,1008,56,5.61,10000,few clouds
7,2026-05-31 06:00:00,310.04,1007,35,5.48,10000,clear sky
8,2026-05-31 09:00:00,314.10,1004,24,4.45,10000,clear sky
9,2026-05-31 12:00:00,314.33,1002,23,6.96,10000,clear sky
10,2026-05-31 15:00:00,306.65,1005,49,2.31,10000,clear sky
11,2026-05-31 18:00:00,306.02,1007,48,2.13,10000,few clouds
12,2026-05-31 21:00:00,304.42,1006,59,2.50,10000,overcast clouds
13,2026-06-01 00:00:00,303.27,1007,63,4.91,10000,overcast clouds
14,2026-06-01 03:00:00,305.02,1009,54,4.47,10000,broken clouds
15,2026-06-01 06:00:00,310.56,1008,34,5.17,10000,scattered clouds
16,2026-06-01 09:00:00,314.60,1005,21,5.30,10000,scattered clouds
17,2026-06-01 12:00:00,314.46,1003,23,6.88,10000,few clouds
18,2026-06-01 15:00:00,309.07,1005,35,3.25,10000,clear sky
19,2026-06-01 18:00:00,305.79,1007,52,2.34,10000,clear sky
20,2026-06-01 21:00:00,303.75,1006,64,3.66,10000,clear sky
21,2026-06-02 00:00:00,303.42,1007,61,4.35,10000,few clouds
22,2026-06-02 03:00:00,304.50,1008,58,4.80,10000,broken clouds
23,2026-06-02 06:00:00,309.66,1007,38,4.88,10000,broken clouds
24,2026-06-02 09:00:00,313.64,1004,25,5.01,10000,clear sky
25,2026-06-02 12:00:00,313.55,1002,25,6.37,10000,clear sky
26,2026-06-02 15:00:00,306.76,1004,49,5.52,10000,clear sky
27,2026-06-02 18:00:00,304.47,1005,61,4.19,10000,scattered clouds
28,2026-06-02 21:00:00,304.50,1005,60,3.25,10000,broken clouds
29,2026-06-03 00:00:00,303.61,1005,62,3.23,10000,broken clouds
30,2026-06-03 03:00:00,305.30,1006,55,5.18,10000,overcast clouds
31,2026-06-03 06:00:00,310.66,1005,36,4.76,10000,broken clouds
32,2026-06-03 09:00:00,314.45,1001,26,4.98,10000,clear sky
33,2026-06-03 12:00:00,312.47,1000,31,7.11,10000,scattered clouds
34,2026-06-03 15:00:00,305.83,1002,54,8.00,10000,broken clouds
35,2026-06-03 18:00:00,307.55,1002,47,5.52,10000,scattered clouds
36,2026-06-03 21:00:00,305.01,1003,55,4.83,10000,light rain
37,2026-06-04 00:00:00,304.23,1003,56,3.63,10000,broken clouds
38,2026-06-04 03:00:00,306.15,1004,48,4.96,10000,clear sky
39,2026-06-04 06:00:00,311.12,1004,35,5.14,10000,clear sky

2iOcFizSJvFzbjTdPqrzeupJapaxfWh93l2iSxnC

In [12]:
import requests
import pandas as pd

In [13]:
api_key='2iOcFizSJvFzbjTdPqrzeupJapaxfWh93l2iSxnC'
url="https://api.nasa.gov/planetary/apod"
result=requests.get(url,params={'api_key':'2iOcFizSJvFzbjTdPqrzeupJapaxfWh93l2iSxnC','date':'2026-05-22'})
data=result.json()
print(data)

{'copyright': 'Luigi Morrone', 'date': '2026-05-22', 'explanation': "This cosmic snapshot covers a field of view over twice as wide as the full Moon within the boundaries of the high-flying constellation Cygnus. Made using astronomical narrowband filters, the image highlights the bright edge of a ring-like nebula traced by the glow of ionized hydrogen and oxygen gas. Embedded in the region's expanse of interstellar clouds, the complex, glowing arcs are sections of shells of material swept up by the wind from Wolf-Rayet star WR 134, the brightest star near image center. Distance estimates put WR 134 about 6,000 light-years away, making this telescopic frame over 100 light-years across. Shedding their outer envelopes in powerful stellar winds, massive Wolf-Rayet stars have burned through their nuclear fuel at a prodigious rate and end their final phase of massive star evolution in a spectacular supernova. Their stellar winds and final supernova explosion enrich the interstellar material with heavy elements to be incorporated in future generations of stars.", 'hdurl': 'https://apod.nasa.gov/apod/image/2605/WR134morrone2048.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'The Nebulous Realm of WR 134', 'url': 'https://apod.nasa.gov/apod/image/2605/WR134morrone1024.jpg'}

In [14]:
api_key='2iOcFizSJvFzbjTdPqrzeupJapaxfWh93l2iSxnC'
url="https://api.nasa.gov/planetary/apod?api_key="+api_key
result=requests.get(url,params={'count':10})
data=result.json()
# print(data)

In [15]:
import requests, json

In [21]:
url='https://jsonplaceholder.typicode.com/posts/1'
response=requests.get(url)
print(response.status_code)
data=response.json()
print(json.dumps(data,indent=5))

200
{
     "userId": 1,
     "id": 1,
     "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
     "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}

In [24]:
print(response.json())
print(type(response.json()))

{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
<class 'dict'>

In [23]:
print(response.text)
print(type(response.text))

{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}
<class 'str'>

In [3]:
url='https://jsonplaceholder.typicode.com/posts'
response=requests.get(url)
print(response.status_code)
data=response.json()
# print(json.dumps(data,indent=5))

200

In [26]:
for i in data[:5]:
    print(i['id'],"-",i['title'])

1 - sunt aut facere repellat provident occaecati excepturi optio reprehenderit
2 - qui est esse
3 - ea molestias quasi exercitationem repellat qui ipsa sit aut
4 - eum et est occaecati
5 - nesciunt quas odio

In [30]:
url='https://jsonplaceholder.typicode.com/posts'
params={'userId':1}
response=requests.get(url,params=params)
print(response.status_code)
data=response.json()
print(len(data))

200
10

In [31]:
response.url

'https://jsonplaceholder.typicode.com/posts?userId=1'

In [32]:
url='https://jsonplaceholder.typicode.com/posts/1'
headers={'User-Agent':'Mozilla/5.0','Accept':'application/json'}
response=requests.get(url,headers=headers)
print(response.status_code)
data=response.json()
print(json.dumps(data,indent=5))

200
{
     "userId": 1,
     "id": 1,
     "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
     "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}

In [33]:
response.headers

{'Date': 'Sat, 30 May 2026 06:26:49 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'access-control-allow-credentials': 'true', 'Cache-Control': 'max-age=43200', 'etag': 'W/"124-yiKdLzqO5gfBrJFrcdJ8Yq0LGnU"', 'expires': '-1', 'nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'pragma': 'no-cache', 'report-to': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=yWDKoM33s0ykZ4m8HUKIycH8yp4%2FEUKSWfXAQUH3IKo%3D\\u0026sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d\\u0026ts=1752712136"}],"max_age":3600}', 'reporting-endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=yWDKoM33s0ykZ4m8HUKIycH8yp4%2FEUKSWfXAQUH3IKo%3D&sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d&ts=1752712136"', 'Server': 'cloudflare', 'vary': 'Origin, Accept-Encoding', 'via': '2.0 heroku-router', 'x-content-type-options': 'nosniff', 'x-powered-by': 'Express', 'x-ratelimit-limit': '1000', 'x-ratelimit-remaining': '999', 'x-ratelimit-reset': '1752712183', 'Age': '19079', 'cf-cache-status': 'HIT', 'Content-Encoding': 'zstd', 'CF-RAY': 'a03bab627c128eef-BOM', 'alt-svc': 'h3=":443"; ma=86400'}

In [34]:
response.headers['Date']

'Sat, 30 May 2026 06:26:49 GMT'

In [38]:
url='https://jsonplaceholder.typicode.com/posts'
new_post={
    'title':'Learning Requests',
    'body':'This is tutorial',
    'userId':1
}

response=requests.post(url,json=new_post)
print(response.status_code)
print(response.json())

201
{'title': 'Learning Requests', 'body': 'This is tutorial', 'userId': 1, 'id': 101}

In [39]:
url='https://jsonplaceholder.typicode.com/posts/1'
new_post={
    'id':1,
    'title':'Updated title',
    'body':'updates body',
    'userId':1
}

response=requests.put(url,json=new_post)
print(response.status_code)
print(response.json())

200
{'id': 1, 'title': 'Updated title', 'body': 'updates body', 'userId': 1}

In [40]:
url='https://jsonplaceholder.typicode.com/posts/1'
new_post={
    'title':'Updated title'
}

response=requests.put(url,json=new_post)
print(response.status_code)
print(response.json())

200
{'title': 'Updated title', 'id': 1}

In [41]:
url='https://jsonplaceholder.typicode.com/posts/1'
new_post={
    'title':'patched title',
}

response=requests.patch(url,json=new_post)
print(response.status_code)
print(response.json())

200
{'userId': 1, 'id': 1, 'title': 'patched title', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [42]:
url='https://jsonplaceholder.typicode.com/posts/1'
response=requests.delete(url)
print(response.status_code)
print(response.json())

200
{}

In [44]:
url='https://picsum.photos/200'
res=requests.get(url)

with open('random_image.png','wb') as f:
    f.write(res.content)

In [45]:
url='https://jsonplaceholder.typicode.com/posts/1'
response=requests.get(url)
data=response.json()

with open('post.json','w') as f:
    json.dump(data,f,indent=5)
print('json file saved')

json file saved

In [46]:
with open('post.json','r') as f:
    l=json.load(f)
print(l)

{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [47]:
import pandas as pd
url='https://jsonplaceholder.typicode.com/posts'
response=requests.get(url)
data=response.json()
df=pd.DataFrame(data)
df

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

In [54]:
url='https://jsonplaceholder.typicode.com/users/1'
response=requests.get(url)
data=response.json()
n=data['name']
un=data['username']
e=data['email']
p=data['phone']
co=data['company']['name']
ci=data['address']['city']
lat=data['address']['geo']['lat']
lng=data['address']['geo']['lng']

print(n)
print(un)
print(e)
print(p)
print(co)
print(ci)
print(lat)
print(lng)

Leanne Graham
Bret
Sincere@april.biz
1-770-736-8031 x56442
Romaguera-Crona
Gwenborough
-37.3159
81.1496

In [68]:
url='https://jsonplaceholder.typicode.com/users'
response=requests.get(url)
data=response.json()
rows=[]
for i in data:
    n=i['name']
    un=i['username']
    e=i['email']
    p=i['phone']
    co=i['company']['name']
    ci=i['address']['city']
    lat=i['address']['geo']['lat']
    lng=i['address']['geo']['lng']
    d={'Name':n,'Username':un, 'Email':e,'Phone':p,'company':co,'City':ci,'Latitude':lat,'Longitude':lng,}
    rows.append(d)
df=pd.DataFrame(rows)
df

,Name,Username,Email,Phone,company,City,Latitude,Longitude
0,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442,Romaguera-Crona,Gwenborough,-37.3159,81.1496
1,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125,Deckow-Crist,Wisokyburgh,-43.9509,-34.4618
2,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447,Romaguera-Jacobson,McKenziehaven,-68.6102,-47.0653
3,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156,Robel-Corkery,South Elvis,29.4572,-164.2990
4,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289,Keebler LLC,Roscoeview,-31.8129,62.5342
5,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,1-477-935-8478 x6430,Considine-Lockman,South Christy,-71.4197,71.7478
6,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,210.067.6132,Johns Group,Howemouth,24.8918,21.8984
7,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,586.493.6943 x140,Abernathy Group,Aliyaview,-14.3990,-120.7677
8,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,(775)976-6794 x41206,Yost and Sons,Bartholomebury,24.6463,-168.8889
9,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,024-648-3804,Hoeger LLC,Lebsackbury,-38.2386,57.2232

In [62]:
json_string='''{
"name":"Alice",
"age":26
}'''

data=json.loads(json_string)
print(data)
print(type(json_string))
print(type(data))

{'name': 'Alice', 'age': 26}
<class 'str'>
<class 'dict'>

In [69]:
url='https://jsonplaceholder.typicode.com/posts'
params={
    '_page':1,
    '_limit':5
}
response=requests.get(url,params=params)
data=response.json()
print(json.dumps(data,indent=5))

[
     {
          "userId": 1,
          "id": 1,
          "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
          "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
     },
     {
          "userId": 1,
          "id": 2,
          "title": "qui est esse",
          "body": "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla"
     },
     {
          "userId": 1,
          "id": 3,
          "title": "ea molestias quasi exercitationem repellat qui ipsa sit aut",
          "body": "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut"
     },
     {
          "userId": 1,
          "id": 4,
          "title": "eum et est occaecati",
          "body": "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit"
     },
     {
          "userId": 1,
          "id": 5,
          "title": "nesciunt quas odio",
          "body": "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque"
     }
]

In [70]:
url='https://jsonplaceholder.typicode.com/posts'
params={
    '_page':1,
    '_limit':5
}
response=requests.get(url,params=params)
data=response.json()
# print(json.dumps(data,indent=5))
for i in data:
    print(i['id'],"-",i['title'])

1 - sunt aut facere repellat provident occaecati excepturi optio reprehenderit
2 - qui est esse
3 - ea molestias quasi exercitationem repellat qui ipsa sit aut
4 - eum et est occaecati
5 - nesciunt quas odio

In [71]:
url='https://jsonplaceholder.typicode.com/posts'
params={
    '_page':2,
    '_limit':5
}
response=requests.get(url,params=params)
data=response.json()
# print(json.dumps(data,indent=5))
for i in data:
    print(i['id'],"-",i['title'])

6 - dolorem eum magni eos aperiam quia
7 - magnam facilis autem
8 - dolorem dolore est ipsam
9 - nesciunt iure omnis dolorem tempora et accusantium
10 - optio molestias id quia eum

In [72]:
url='https://jsonplaceholder.typicode.com/posts'
params={
    '_page':3,
    '_limit':5
}
response=requests.get(url,params=params)
data=response.json()
# print(json.dumps(data,indent=5))
for i in data:
    print(i['id'],"-",i['title'])

11 - et ea vero quia laudantium autem
12 - in quibusdam tempore odit est dolorem
13 - dolorum ut in voluptas mollitia et saepe quo animi
14 - voluptatem eligendi optio
15 - eveniet quod temporibus

In [74]:
url='https://jsonplaceholder.typicode.com/posts'
page=1
while page<=3:
    params={'_page':page,'_limit':5}
    response=requests.get(url,params=params)
    data=response.json()
    # print(json.dumps(data,indent=5))
    for i in data:
        print(i['id'],"-",i['title'])
    page+=1

1 - sunt aut facere repellat provident occaecati excepturi optio reprehenderit
2 - qui est esse
3 - ea molestias quasi exercitationem repellat qui ipsa sit aut
4 - eum et est occaecati
5 - nesciunt quas odio
6 - dolorem eum magni eos aperiam quia
7 - magnam facilis autem
8 - dolorem dolore est ipsam
9 - nesciunt iure omnis dolorem tempora et accusantium
10 - optio molestias id quia eum
11 - et ea vero quia laudantium autem
12 - in quibusdam tempore odit est dolorem
13 - dolorum ut in voluptas mollitia et saepe quo animi
14 - voluptatem eligendi optio
15 - eveniet quod temporibus

In [2]:
url='https://jsonplaceholder.typicode.com/posts'
token='my_token'
headers={'Authorization':f"Bearer {token}"}
response=requests.get(url,headers=headers)
print(response.status_code)
# print(response.json())

200

In [4]:
res=requests.get('https://api.github.com/rate_limit')
data=res.json()

print('limit : ',data['rate']['limit'])
print('used : ',data['rate']['used'])
print('remaining : ',data['rate']['remaining'])
print('reset : ',data['rate']['reset'])

limit :  60
used :  60
remaining :  0
reset :  1780288022

In [5]:
for i in range(70):
    r=requests.get('https://api.github.com/users/octacat')
    print(i+1,r.status_code)
    if r.status_code==403:
        data=r.json()
        if "API rate limit exceeded" in data.get("message",""):
            print("rate limit exceeded")
            print(data['message'])
            break

1 403
rate limit exceeded
API rate limit exceeded for 120.72.91.122. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

In [9]:
from datetime import datetime
import requests

r=requests.get('https://api.github.com/rate_limit')
data=r.json()
reset_stamp=data['rate']['reset']
reset_time=datetime.fromtimestamp(reset_stamp).strftime("%y-%m-%d %H:%M:%S")   #strf- string formated
print(reset_time)

26-06-01 09:57:02